create table ApplicationException (
  identity bigint generated by default as identity (start with 1),
  checksum varchar(255),
  exceptionTrace varchar(255),
  
  primary key (identity)
);

create table ApplicationExceptionOccurrence (
  identity bigint generated by default as identity (start with 1),
  occured timestamp,
  exception_identity bigint,
  primary key (identity)
);

alter table ApplicationExceptionOccurrence
add constraint FK56A30DB2E2801A1
foreign key (exception_identity) references ApplicationException;

create unique index APPLICATION_EXCEPTION_PK on ApplicationException (identity);

create unique index APPLICATION_EXCEPTION_OCCURRENCE_PK on ApplicationExceptionOccurrence (identity);
create index APPLICATION_EXCEPTION_OCCURRENCE_FK1 on ApplicationExceptionOccurrence (exception_identity);