create table ApplicationException (
  identity bigint generated by default as identity (start with 1),
  checksum varchar(255),
  exceptionTrace varchar(255),
  primary key (identity)
);

create table ApplicationExceptionEvent (
  identity bigint generated by default as identity (start with 1),
  occured timestamp, exception_identity bigint,
  primary key (identity)
);

alter table ApplicationExceptionEvent
add constraint FK56A30DB2E2801A1
foreign key (exception_identity) references ApplicationException;